development:
  clients:
    default:
      uri: <%= "mongodb://#{ENV['DB_USER']}:#{ENV['DB_PASS']}@#{ENV['DB_HOST']}?retryWrites=false" %>
      options:
        server_selection_timeout: 5
        retryWrites: false

test:
  clients:
    default:
      database: ruby_api_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
