development:
  # Configure available database sessions. (required)
sessions:
   default:
      uri: <%= "mongodb://#{ENV['DB_USER']}:#{ENV['DB_PASS']}@#{ENV['DB_HOST']}" %> 
      options: 
        consistency: :strong
        max_retries: 30
        retry_interval: 1
        timeout: 15

test:
  clients:
    default:
      database: ruby_api_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
